adding sureness config
wooorm/retext-profanities pull request #17
Opened 2018-12-06 08:35 UTC by mansona

This is a relatively small PR that allows the end user to define a "minimum sureness" config value. For example, if you do not want to have errors/warnings for things that are defined as "0 sureness" from cuss then you can add the following config: 

```
retext()
    .use(english, {sureness: 1})
```

which will cause it to only report for words with a sureness of 1 or more.

Let me know if you would like me to change anything 👍

2018-12-06 10:36 UTC, wooorm requested changes
Hey that’s nice, thanks! 👍

Two nits:

* Could you exit early? Instead of `if (rating >= sureness) { ... }`, do `if (rating <= sureness) { return }`
* I wonder if, from sureness, it makes sense that it’s inclusive, so that if you do `1`, `severity: 1` and `severity: 2` are included? Not sure how to make that more clear, but maybe you have thoughts? Maybe it’s fine the way it is tho?

2018-12-06 12:54 UTC, mansona commented
@wooorm I have changed the check to make it exit early. I was trying to be over cautious 😂 

As for the sureness config, the only thing that I could think of is changing the name to be `minSureness` (which is how it's working right now). I think semantically it makes sense for it to be a "minimum level" and work similar to how people use log-level config but we could make it more explicit in its name if you would prefer 👍

2018-12-07 11:48 UTC, wooorm approved these changes

2018-12-07 11:49 UTC, wooorm commented
> As for the sureness config

Yah, I don’t think `minSureness` is nicer 🤔 let’s keep it like this! 👍

2018-12-07 11:49 UTC, merged

2018-12-07 11:53 UTC, wooorm commented
Landed, thanks @mansona 💪